# Generated by Django 5.0.5 on 2024-05-08 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('debit_operation', models.CharField(choices=[('increase', 'increase'), ('decrease', 'decrease')], max_length=15, verbose_name='Opération au débit')),
                ('credit_operation', models.CharField(max_length=15, verbose_name='Opération au crédit')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('amount', models.IntegerField(default=0, verbose_name='Montant')),
            ],
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nom')),
                ('prompt', models.TextField(verbose_name='Prompte')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('solde', models.IntegerField(default=0, verbose_name='Solde')),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.accounttype')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libelle')),
                ('ref', models.CharField(max_length=100, unique=True, verbose_name='Ref')),
                ('amount', models.IntegerField(verbose_name='Montant')),
                ('type_operation', models.CharField(blank=True, choices=[('Achat', 'Achat'), ('Vente', 'Vente')], max_length=10, verbose_name='Type')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé à')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour à')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.journal')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom de famille')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Adresse email')),
                ('phone_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de téléphone')),
                ('sexe', models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], max_length=1, verbose_name='Sexe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.person'),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('localisation_gps', models.CharField(blank=True, default='', max_length=100, verbose_name='Localisation GPS')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('town', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('person', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.person'),
        ),
    ]
