# Generated by Django 5.0.5 on 2024-05-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Montant'),
        ),
    ]
