# Generated by Django 5.0.5 on 2024-05-08 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(blank=True, choices=[('débit', 'débit'), ('crédit', 'crédit')], max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='account',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.accountcategory'),
        ),
    ]
