# Generated by Django 5.0.5 on 2024-05-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accountcategory_alter_operation_type_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='solde_credit',
            field=models.IntegerField(default=0, verbose_name='Crédit'),
        ),
        migrations.AddField(
            model_name='account',
            name='solde_debit',
            field=models.IntegerField(default=0, verbose_name='Debit'),
        ),
    ]
