# Generated by Django 4.2.11 on 2024-05-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_journal_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='profil',
        ),
    ]
