# Generated by Django 5.0.5 on 2024-05-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_solde_credit_account_solde_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='piece_complatble'),
        ),
        migrations.AlterField(
            model_name='accountcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='accountcategory',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ref'),
        ),
    ]
