# Generated by Django 5.0.5 on 2024-05-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_operation_fichier_alter_accountcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
    ]
