# Generated by Django 4.2.11 on 2024-05-07 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_person_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='business',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quartier'),
        ),
        migrations.AlterField(
            model_name='business',
            name='localisation_gps',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Localisation GPS'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='business',
            name='person',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.person'),
        ),
        migrations.AlterField(
            model_name='business',
            name='town',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
    ]
