# Generated by Django 4.2.11 on 2024-05-09 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_accounttype_name_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='etat',
        ),
        migrations.AddField(
            model_name='budget',
            name='cloturer',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
