# Generated by Django 4.2.11 on 2024-05-07 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_description_operation_libelle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.accounttype'),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro'),
        ),
    ]
